name: master
on:
  push:
    branches:
      - master
jobs:
  unit-test:
    name: Generate and test a sample application
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        cats: ['cats=true', 'cats=false']
        build_info: ['build_info=true', 'build_info=false']
        dotenv: ['dotenv=true', 'dotenv=false']
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          path: 'scala-giter8'
      - name: Set up the JDK, Giter8, and SBT
        uses: coursier/setup-action@v1
        with:
          jvm: adopt:11
          apps: giter8 sbt
      - name: Generate the application
        run: g8 file://scala-giter8 --name=test-app --${{ matrix.cats }} --${{ matrix.build_info }} --${{ matrix.dotenv }}
      - name: Run the application
        run: cd test-app && sbt run
      - name: Unit test the application
        run: cd test-app && sbt test
